//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorLibro
    {
        public int IdAutorLibro { get; set; }
        public Nullable<int> IdAutor { get; set; }
        public Nullable<int> IdLibro { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
