//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibroEditorial
    {
        public int IdLibroEditorial { get; set; }
        public Nullable<int> IdLibro { get; set; }
        public Nullable<int> IdEditorial { get; set; }
    
        public virtual Editorial Editorial { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
