//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public Libro()
        {
            this.AutorLibroes = new HashSet<AutorLibro>();
            this.LibroEditorials = new HashSet<LibroEditorial>();
        }
    
        public int IdLibro { get; set; }
        public string TituloLibro { get; set; }
        public Nullable<short> AñoPublicacion { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual ICollection<AutorLibro> AutorLibroes { get; set; }
        public virtual ICollection<LibroEditorial> LibroEditorials { get; set; }
    }
}
